spring:
  datasource:
    url: jdbc:h2:mem:hotel
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  sql:
    show: true


#http://localhost:8080/h2-console/